/**
 * @finch/design-tokens — Constitution §34–§35, docs/design/DESIGN-PRINCIPLES.md.
 *
 * Source of truth: the DTCG JSON files in ./tokens (the same format Figma Variables are
 * exported to and imported from — docs/design/FIGMA.md). This module resolves aliases,
 * exposes typed theme maps and renders CSS custom properties for web and desktop.
 *
 * Rules enforced by the tests next to this file:
 *   - every alias resolves to a primitive;
 *   - semantic layers never contain raw values (only aliases);
 *   - every text/surface and foreground/background pair meets WCAG 2.2 AA in both themes.
 */
import primitivesJson from './tokens/primitives.json' with { type: 'json' };
import lightJson from './tokens/semantic.light.json' with { type: 'json' };
import darkJson from './tokens/semantic.dark.json' with { type: 'json' };

export type TokenValue = string | number | readonly (string | number)[];
export type ThemeName = 'light' | 'dark';

/** A DTCG group: nested objects whose leaves have a `$value`. */
type TokenGroup = Readonly<Record<string, unknown>>;

const ALIAS = /^\{([^}]+)\}$/;

/** Flattens a DTCG tree into `dot.path → $value` (metadata keys starting with `$` are skipped). */
export function flatten(tree: TokenGroup, prefix = ''): Map<string, TokenValue> {
  const out = new Map<string, TokenValue>();
  for (const [key, node] of Object.entries(tree)) {
    if (key.startsWith('$') || typeof node !== 'object' || node === null) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    const record = node as TokenGroup;
    if ('$value' in record) out.set(path, record['$value'] as TokenValue);
    else for (const [k, v] of flatten(record, path)) out.set(k, v);
  }
  return out;
}

export const primitives: ReadonlyMap<string, TokenValue> = flatten(primitivesJson);

/** Resolves `{path}` aliases against primitives; throws on unknown or circular references. */
export function resolve(value: TokenValue, seen: readonly string[] = []): TokenValue {
  if (typeof value !== 'string') return value;
  const match = ALIAS.exec(value);
  if (!match) return value;
  const path = match[1] ?? '';
  if (seen.includes(path)) throw new Error(`Circular token alias: ${[...seen, path].join(' → ')}`);
  const target = primitives.get(path);
  if (target === undefined) throw new Error(`Unknown token alias: {${path}}`);
  return resolve(target, [...seen, path]);
}

function buildTheme(tree: TokenGroup): ReadonlyMap<string, TokenValue> {
  const resolved = new Map<string, TokenValue>();
  for (const [path, value] of flatten(tree)) resolved.set(path, resolve(value));
  return resolved;
}

/** Raw (unresolved) semantic layers — exposed for the no-raw-values test and Figma export. */
export const semanticSource: Readonly<Record<ThemeName, ReadonlyMap<string, TokenValue>>> = {
  light: flatten(lightJson),
  dark: flatten(darkJson),
};

/** Fully resolved semantic themes. Components consume these names only. */
export const themes: Readonly<Record<ThemeName, ReadonlyMap<string, TokenValue>>> = {
  light: buildTheme(lightJson),
  dark: buildTheme(darkJson),
};

/** `color.text.primary` → `--finch-color-text-primary`. */
export function cssVarName(path: string): string {
  return `--finch-${path
    .replace(/\./g, '-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()}`;
}

function cssValue(value: TokenValue): string {
  if (Array.isArray(value)) {
    const items = value as readonly (string | number)[];
    return items.every((v) => typeof v === 'number')
      ? `cubic-bezier(${items.join(', ')})`
      : items.map((v) => (typeof v === 'string' && /\s/.test(v) ? `"${v}"` : String(v))).join(', ');
  }
  return String(value);
}

function declarations(map: ReadonlyMap<string, TokenValue>, indent: string): string {
  return [...map]
    .map(([path, value]) => `${indent}${cssVarName(path)}: ${cssValue(value)};`)
    .join('\n');
}

/**
 * Renders the complete stylesheet: primitives-derived scales (type, space, radius, motion) on
 * :root, the light theme by default, the dark theme under `prefers-color-scheme` and under an
 * explicit `[data-theme]` override.
 */
export function renderCss(): string {
  const nonColor = new Map([...primitives].filter(([path]) => !path.startsWith('color.')));
  return [
    '/* GENERATED by @finch/design-tokens — do not edit. Source: packages/design-tokens/src/tokens */',
    `:root {\n${declarations(nonColor, '  ')}\n${declarations(themes.light, '  ')}\n  color-scheme: light;\n}`,
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme='light']) {\n${declarations(themes.dark, '    ')}\n    color-scheme: dark;\n  }\n}`,
    `[data-theme='dark'] {\n${declarations(themes.dark, '  ')}\n  color-scheme: dark;\n}`,
    '',
  ].join('\n\n');
}

// ---------------------------------------------------------------------------
// Contrast (WCAG 2.x relative luminance)
// ---------------------------------------------------------------------------
function channel(hex: string, offset: number): number {
  const c = Number.parseInt(hex.slice(offset, offset + 2), 16) / 255;
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

export function luminance(hex: string): number {
  const h = hex.replace('#', '');
  if (!/^[0-9a-fA-F]{6}$/.test(h)) throw new Error(`Expected #RRGGBB, got ${hex}`);
  return 0.2126 * channel(h, 0) + 0.7152 * channel(h, 2) + 0.0722 * channel(h, 4);
}

/** WCAG contrast ratio between two #RRGGBB colors (1–21). */
export function contrastRatio(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x) as [number, number];
  return (hi + 0.05) / (lo + 0.05);
}

/** Reads a resolved color from a theme, failing loudly for unknown names. */
export function color(theme: ThemeName, path: string): string {
  const value = themes[theme].get(path);
  if (typeof value !== 'string') throw new Error(`Unknown color token ${path} in ${theme}`);
  return value;
}
