/**
 * Formula Registry entries for the cash-flow formulas (task S1-01).
 * Spec: docs/financial-formulas/colombia-credit.md §7–§8. Vectors: test/vectors/*.json,
 * generated by an independent Python implementation (never by this code).
 */
import { registerFormula } from '../formula-registry.js';

const SPEC = 'docs/financial-formulas/colombia-credit.md';

registerFormula({
  formulaId: 'cashflow.forecast_30d',
  version: 1,
  purpose:
    'Project end-of-day balances for the next 30 days from known income and obligations, ' +
    'and find the first day below the user’s buffer and the lowest balance.',
  inputs: [
    { name: 'today', unit: 'date', description: 'First day of the forecast, YYYY-MM-DD.' },
    { name: 'startingBalance', unit: 'minor units', description: 'Before today’s events.' },
    { name: 'buffer', unit: 'minor units', description: 'Minimum balance to keep.' },
    {
      name: 'calendar',
      unit: 'parameter',
      description: 'Weekend weekdays and holidays from jurisdictions/<CC>/calendar.',
    },
    {
      name: 'events',
      unit: 'list',
      description: 'Income or obligation: date, shift rule, amount + truth class, or history.',
    },
  ],
  outputUnit: 'minor units per day; date; truth class',
  rounding: 'None: sums of minor units. Variable income uses an observed amount (nearest rank).',
  assumptions: [
    'Each point is an end-of-day balance; d = today .. today + 30.',
    'Events on non-business days move by their shift rule (next or previous business day).',
    'Variable income = ⌈0.25·n⌉-th smallest of 3–6 past amounts, and the series is ESTIMATED.',
  ],
  reference: `${SPEC} §7.`,
  edgeCases: [
    'Events whose effective date falls outside the horizon are ignored.',
    'The minimum reports its first occurrence.',
    'GENERATED_NARRATIVE inputs are refused (UNTRUSTED_INPUT).',
  ],
  implementationPath: 'packages/financial-engine/src/cashflow/forecast.ts#forecast30d',
  testVectors: [
    {
      description: 'deficit: first day below the buffer and its shortfall',
      inputs: {
        today: '2026-10-15',
        startingBalance: '80000000',
        buffer: '20000000',
        events: 'rent:OBLIGATION:2026-10-20:90000000;card:OBLIGATION:2026-10-25:60000000',
      },
      expected: '2026-10-20:30000000',
    },
    {
      description: 'no deficit',
      inputs: {
        today: '2026-10-15',
        startingBalance: '150000000',
        buffer: '20000000',
        events: 'rent:OBLIGATION:2026-10-20:90000000;salary:INCOME:2026-10-30:420000000',
      },
      expected: 'none',
    },
  ],
});

registerFormula({
  formulaId: 'cashflow.safe_to_spend',
  version: 1,
  purpose:
    'What can be spent today without the projected balance falling below the buffer ' +
    'before the next income.',
  inputs: [
    {
      name: 'forecast',
      unit: 'cashflow.forecast_30d@1 inputs',
      description: 'The same inputs as the 30-day forecast.',
    },
  ],
  outputUnit: 'minor units; date; boolean; truth class',
  rounding: 'None: a difference of minor units, floored at zero.',
  assumptions: [
    'STS = max(0, min over [today, next income] of balance − buffer).',
    'Next income is the first income day strictly after today inside the horizon.',
    'Without a known next income, the whole 30-day horizon is used and reported as such.',
  ],
  reference: `${SPEC} §8.`,
  edgeCases: [
    'Obligations before payday that exceed the balance: STS = 0.',
    'No known next income: nextIncomeKnown = false, window = the horizon.',
  ],
  implementationPath: 'packages/financial-engine/src/cashflow/safe-to-spend.ts#safeToSpend',
  testVectors: [
    {
      description: 'positive',
      inputs: {
        today: '2026-10-15',
        startingBalance: '150000000',
        buffer: '20000000',
        events:
          'rent:OBLIGATION:2026-10-20:90000000;salary:INCOME:2026-10-30:420000000;' +
          'card:OBLIGATION:2026-11-05:60000000',
      },
      expected: '40000000',
    },
    {
      description: 'zero',
      inputs: {
        today: '2026-10-15',
        startingBalance: '80000000',
        buffer: '20000000',
        events:
          'rent:OBLIGATION:2026-10-20:90000000;card:OBLIGATION:2026-10-25:60000000;' +
          'salary:INCOME:2026-10-30:420000000',
      },
      expected: '0',
    },
    {
      description: 'no known next income',
      inputs: {
        today: '2026-10-15',
        startingBalance: '200000000',
        buffer: '30000000',
        events: 'rent:OBLIGATION:2026-10-20:90000000;card:OBLIGATION:2026-11-10:50000000',
      },
      expected: '30000000',
    },
  ],
});
