/**
 * Formula Registry entries for the personal-finance budget formulas (task S1-02).
 * Spec: docs/financial-formulas/personal-finance.md §1–§2. Vectors: test/vectors/budget.*.json,
 * generated by an independent Python implementation (never by this code).
 */
import { registerFormula } from '../formula-registry.js';

const SPEC = 'docs/financial-formulas/personal-finance.md';

registerFormula({
  formulaId: 'budget.allocate',
  version: 1,
  purpose:
    'Split an income across obligations, debt minimums, pay-yourself-first savings, the ' +
    'buffer, goals and a surplus strategy, reporting a deficit instead of hiding it.',
  inputs: [
    { name: 'income', unit: 'minor units', description: 'The income being allocated.' },
    { name: 'nextIncome', unit: 'date', description: 'Items due after it wait for that income.' },
    { name: 'obligations', unit: 'list', description: 'id, amount, due date.' },
    { name: 'debts', unit: 'list', description: 'id, minimum, due date, monthly rate, balance.' },
    { name: 'rule', unit: 'enum', description: 'NONE | RULE_50_30_20 | PAY_YOURSELF_FIRST(p).' },
    { name: 'buffer', unit: 'minor units', description: 'Target, current, cap per cycle.' },
    { name: 'goals', unit: 'list', description: 'id, priority, target date, suggested amount.' },
    { name: 'strategy', unit: 'enum', description: 'DEBT_AVALANCHE | SAVINGS for the surplus.' },
    { name: 'surplusShare', unit: 'fraction', description: 'Share of the surplus, 0..1.' },
  ],
  outputUnit: 'minor units per allocation line; free; shortfall',
  rounding: 'HALF_EVEN to the minor unit, only for the pay-yourself-first and surplus shares.',
  assumptions: [
    'Layers run in a fixed order and each consumes what is left.',
    'RULE_50_30_20 means 20 % pay-yourself-first in version 1.',
    'Obligations and minimums due after the next income are left for that income.',
  ],
  reference: `${SPEC} §1.`,
  edgeCases: [
    'Obligations and minimums above the income: shortfall reported, layers 3+ get nothing.',
    'Goals funded partially when the remainder runs out; free can be 0.',
    'DEBT_AVALANCHE without debts sends the surplus to savings.',
  ],
  implementationPath: 'packages/financial-engine/src/budget/allocate.ts#budgetAllocate',
  testVectors: [
    {
      description: 'base plan (vector 1 inputs), free/shortfall',
      inputs: { income: '450000000' },
      expected: '39000000/0',
    },
    {
      description: 'deficit with the same obligations, free/shortfall',
      inputs: { income: '200000000' },
      expected: '0/27000000',
    },
  ],
});

registerFormula({
  formulaId: 'budget.envelope_state',
  version: 1,
  purpose: 'Spent, available and the 80 % / 100 % alert of one budget envelope in a cycle.',
  inputs: [
    { name: 'allocated', unit: 'minor units', description: 'Amount assigned for the cycle.' },
    { name: 'expenses', unit: 'minor units', description: 'Expenses booked to the envelope.' },
    { name: 'transfersIn', unit: 'minor units', description: 'Moved in from other envelopes.' },
    { name: 'transfersOut', unit: 'minor units', description: 'Moved out to other envelopes.' },
  ],
  outputUnit: 'minor units; alert enum',
  rounding: 'None: sums of minor units; the 80 % test is exact (5·spent ≥ 4·budget).',
  assumptions: ['Transfers change the budget that alerts are measured against.'],
  reference: `${SPEC} §2.`,
  edgeCases: [
    'No spending: no alert, even for an empty envelope.',
    'Overspending: available goes negative and the alert is LIMIT_100.',
  ],
  implementationPath: 'packages/financial-engine/src/budget/envelope.ts#envelopeState',
  testVectors: [
    {
      description: '35 % spent',
      inputs: { allocated: '100000000', spent: '35000000' },
      expected: 'NONE',
    },
    {
      description: 'exactly 80 %',
      inputs: { allocated: '100000000', spent: '80000000' },
      expected: 'WARN_80',
    },
    {
      description: '115 %',
      inputs: { allocated: '100000000', spent: '115000000' },
      expected: 'LIMIT_100',
    },
  ],
});
