/**
 * Formula Registry entries for the Colombian credit engine (task S1-01).
 * Spec: docs/financial-formulas/colombia-credit.md. Vectors: test/vectors/*.json,
 * generated by an independent Python `decimal` implementation (never by this code).
 */
import { registerFormula } from '../formula-registry.js';

const SPEC = 'docs/financial-formulas/colombia-credit.md';

registerFormula({
  formulaId: 'rate.convert',
  version: 1,
  purpose:
    'Convert an interest rate between quoting conventions (effective or nominal, ' +
    'compounding frequency, in arrears or in advance) through the effective annual rate.',
  inputs: [
    { name: 'rate', unit: 'fraction', description: 'The rate as quoted (0.023 = 2.3 %).' },
    { name: 'from', unit: 'quote', description: 'BASIS/PERIODS/TIMING of the input rate.' },
    { name: 'to', unit: 'quote', description: 'BASIS/PERIODS/TIMING of the output rate.' },
  ],
  outputUnit: 'fraction',
  rounding:
    'None inside the formula: 40 significant digits, half-even, at every step. Display ' +
    'rounding (2 decimals of a percentage) is an explicit caller decision.',
  assumptions: [
    'Nominal rates divide evenly into periodic rates: i_p = N / m.',
    'In advance and in arrears are related per period: i_v = i_a / (1 − i_a).',
    'Compounding frequencies are limited to m ∈ {1, 2, 4, 6, 12, 360, 365}.',
  ],
  reference: `${SPEC} §1; standard compound-interest equivalence of rates.`,
  edgeCases: [
    'A rate in advance of 100 % or more per period is rejected (RATE_OUT_OF_DOMAIN).',
    'Negative rates are rejected unless the caller passes allowNegative (spec §1).',
    'An unsupported frequency or malformed quote is rejected (UNSUPPORTED_QUOTE).',
    'Rate 0 converts to 0 in every convention.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/rate.ts#convertRate',
  testVectors: [
    {
      description: '2.3 % MV → EA',
      inputs: { rate: '0.023', from: 'EFFECTIVE/12/ARREARS', to: 'EFFECTIVE/1/ARREARS' },
      expected: '0.3137344983996021269289886802331443',
    },
    {
      description: '24 % EA → MV',
      inputs: { rate: '0.24', from: 'EFFECTIVE/1/ARREARS', to: 'EFFECTIVE/12/ARREARS' },
      expected: '0.0180875824835106745313530841617514',
    },
    {
      description: '2 % monthly in advance → in arrears',
      inputs: { rate: '0.02', from: 'EFFECTIVE/12/ADVANCE', to: 'EFFECTIVE/12/ARREARS' },
      expected: '0.02040816326530612244897959183673469',
    },
    {
      description: 'rate 1 in advance is out of domain',
      inputs: { rate: '1', from: 'EFFECTIVE/12/ADVANCE', to: 'EFFECTIVE/1/ARREARS' },
      expected: 'RATE_OUT_OF_DOMAIN',
    },
  ],
});

registerFormula({
  formulaId: 'amortization.french',
  version: 1,
  purpose:
    'Fixed-instalment (French system) amortization schedule: instalment, per-period ' +
    'interest and principal, balance, total interest and total paid.',
  inputs: [
    { name: 'principal', unit: 'minor units', description: 'Amount lent, strictly positive.' },
    { name: 'currency', unit: 'ISO 4217', description: 'Currency of the principal.' },
    { name: 'rate', unit: 'fraction per period', description: 'Effective periodic rate ≥ 0.' },
    { name: 'periods', unit: 'integer', description: 'Number of instalments, 1..1200.' },
  ],
  outputUnit: 'minor units',
  rounding:
    'HALF_EVEN to the minor unit for the instalment and for each period’s interest. The ' +
    'last instalment pays the remaining balance plus its interest.',
  assumptions: [
    'Constant periodic rate for the whole term.',
    'Payments at the end of each period (in arrears).',
    'Insurance, fees and taxes are not part of this formula (see credit.total_cost).',
  ],
  reference: `${SPEC} §2; standard annuity-immediate present value.`,
  edgeCases: [
    'Rate 0: C = P / n, residue in the last instalment.',
    'One period: a single payment of principal plus interest.',
    'The last instalment may be above or below C by the accumulated rounding residue.',
    'Amounts too small for the term in whole minor units are rejected ' +
      '(UNAMORTIZABLE_IN_MINOR_UNITS).',
  ],
  implementationPath: 'packages/financial-engine/src/credit/french.ts#frenchAmortization',
  testVectors: [
    {
      description: 'COP 10,000,000 at 1.6 % MV over 36 months: instalment',
      inputs: { principal: '1000000000', currency: 'COP', rate: '0.016', periods: '36' },
      expected: '36757218',
    },
    {
      description: 'zero rate over 3 periods: instalment',
      inputs: { principal: '10000000', currency: 'COP', rate: '0', periods: '3' },
      expected: '3333333',
    },
    {
      description: '360 months at 0.95 % MV: instalment',
      inputs: { principal: '25000000000', currency: 'COP', rate: '0.0095', periods: '360' },
      expected: '245667153',
    },
    {
      description: 'zero periods is rejected',
      inputs: { principal: '100000', currency: 'COP', rate: '0.01', periods: '0' },
      expected: 'INVALID_TERM',
    },
  ],
});

registerFormula({
  formulaId: 'credit.total_cost',
  version: 1,
  purpose:
    'Total cost of a fixed-instalment credit including insurance, fees, upfront costs and ' +
    'GMF, and its real effective annual rate (IRR of the borrower’s monthly cash flows).',
  inputs: [
    { name: 'principal', unit: 'minor units', description: 'Amount lent.' },
    { name: 'currency', unit: 'ISO 4217', description: 'Currency of every amount.' },
    { name: 'rate', unit: 'fraction per month', description: 'Effective monthly loan rate.' },
    { name: 'periods', unit: 'months', description: 'Number of monthly instalments.' },
    { name: 'upfrontCosts', unit: 'minor units', description: 'Deducted from the disbursement.' },
    {
      name: 'insuranceBasis',
      unit: 'enum',
      description: 'NONE | OUTSTANDING (rate × balance before payment) | ORIGINAL | FIXED.',
    },
    { name: 'handlingFee', unit: 'minor units', description: 'Charged every month.' },
    { name: 'otherCharges', unit: 'minor units', description: 'Charged every month.' },
    { name: 'gmfRate', unit: 'fraction', description: 'Tax on each debit; defaults to 0.' },
  ],
  outputUnit: 'minor units (totals); fraction (monthly IRR, effective annual rate)',
  rounding:
    'Instalment and interest as amortization.french@1; insurance and GMF HALF_EVEN to the ' +
    'minor unit per period. IRR by bisection to a bracket width of 1e−12 (≤ 200 iterations).',
  assumptions: [
    'Monthly periods; the effective annual rate is (1 + r)^12 − 1.',
    'Upfront costs are paid at disbursement (t = 0); every other charge at each instalment.',
    'GMF applies to the whole debit when the caller supplies a rate; exemptions are a ' +
      'jurisdiction decision made before calling (spec §3, VERIFY).',
  ],
  reference: `${SPEC} §3; internal rate of return of a loan's cash flows.`,
  edgeCases: [
    'No charges: the IRR equals the loan rate up to minor-unit rounding.',
    'Zero rate and no charges: IRR exactly 0.',
    'Upfront costs ≥ principal, negative charges or insurance rates: INVALID_CHARGES.',
    'GMF rate outside [0, 1): RATE_OUT_OF_DOMAIN.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/total-cost.ts#totalCost',
  testVectors: [
    {
      description: 'no charges: total cost equals total interest',
      inputs: { principal: '1000000000', currency: 'COP', rate: '0.016', periods: '36' },
      expected: '323259857',
    },
    {
      description: 'upfront costs of 2 %: total cost',
      inputs: {
        principal: '1000000000',
        currency: 'COP',
        rate: '0.016',
        periods: '36',
        upfrontCosts: '20000000',
      },
      expected: '343259857',
    },
    {
      description: 'zero-rate loan with an upfront fee: total cost',
      inputs: {
        principal: '120000000',
        currency: 'COP',
        rate: '0',
        periods: '12',
        upfrontCosts: '3000000',
      },
      expected: '3000000',
    },
    {
      description: 'upfront costs equal to the principal are rejected',
      inputs: {
        principal: '1000000',
        currency: 'COP',
        rate: '0.01',
        periods: '12',
        upfrontCosts: '1000000',
      },
      expected: 'INVALID_CHARGES',
    },
  ],
});

registerFormula({
  formulaId: 'credit.usury_check',
  version: 1,
  purpose:
    'Compare the agreed remunerative rate with the certified usury rate, both effective ' +
    'annual, and report whether the certification applies on the evaluation date.',
  inputs: [
    { name: 'agreedRateEA', unit: 'fraction', description: 'Agreed rate, effective annual.' },
    {
      name: 'usuryRateEA',
      unit: 'fraction',
      description: 'Certified usury rate for the credit type, with its source.',
    },
    { name: 'validFrom', unit: 'date', description: 'Certification start, YYYY-MM-DD.' },
    { name: 'validTo', unit: 'date', description: 'Certification end, YYYY-MM-DD.' },
    { name: 'asOf', unit: 'date', description: 'Evaluation date, YYYY-MM-DD.' },
  ],
  outputUnit: 'status (BELOW | AT_OR_ABOVE), percentage points, CURRENT | STALE',
  rounding: 'None: the margin is exact; display rounding is the caller’s decision.',
  assumptions: [
    'Both rates are effective annual (convert with rate.convert@1 first).',
    'Which charges count for usury purposes is a legal question; this formula compares ' +
      'rates only and never states that a charge is illegal (spec §4, D-07).',
  ],
  reference: `${SPEC} §4; Commercial Code art. 884 (usury = 1.5 × certified banking rate).`,
  edgeCases: [
    'A rate equal to the usury rate is AT_OR_ABOVE.',
    'An evaluation date outside the certification window yields STALE, not an error.',
    'A window that ends before it starts: INVALID_VALIDITY_PERIOD.',
    'A non-calendar date: INVALID_DATE.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/usury.ts#usuryCheck',
  testVectors: [
    {
      description: 'below the usury rate',
      inputs: {
        agreedRateEA: '0.24',
        usuryRateEA: '0.2862',
        validFrom: '2026-10-01',
        validTo: '2026-10-31',
        asOf: '2026-10-15',
      },
      expected: 'BELOW',
    },
    {
      description: 'equal to the usury rate',
      inputs: {
        agreedRateEA: '0.2862',
        usuryRateEA: '0.2862',
        validFrom: '2026-10-01',
        validTo: '2026-10-31',
        asOf: '2026-10-01',
      },
      expected: 'AT_OR_ABOVE',
    },
    {
      description: 'above the usury rate',
      inputs: {
        agreedRateEA: '0.3137',
        usuryRateEA: '0.2862',
        validFrom: '2026-10-01',
        validTo: '2026-10-31',
        asOf: '2026-10-31',
      },
      expected: 'AT_OR_ABOVE',
    },
    {
      description: 'inverted validity window is rejected',
      inputs: {
        agreedRateEA: '0.2',
        usuryRateEA: '0.28',
        validFrom: '2026-10-31',
        validTo: '2026-10-01',
        asOf: '2026-10-15',
      },
      expected: 'INVALID_VALIDITY_PERIOD',
    },
  ],
});

registerFormula({
  formulaId: 'credit.compare_refinance',
  version: 1,
  purpose:
    'Compare keeping a debt with refinancing its balance under an offer: instalment change, ' +
    'nominal and present-value savings, break-even month and the longer-term alert.',
  inputs: [
    { name: 'balance', unit: 'minor units', description: 'Outstanding balance to refinance.' },
    { name: 'currency', unit: 'ISO 4217', description: 'Currency of every amount.' },
    { name: 'currentRate', unit: 'fraction per month', description: 'Current effective rate.' },
    { name: 'currentPeriods', unit: 'months', description: 'Remaining instalments.' },
    { name: 'currentCharges', unit: 'minor units', description: 'Monthly charges today.' },
    { name: 'offerRate', unit: 'fraction per month', description: 'Offered effective rate.' },
    { name: 'offerPeriods', unit: 'months', description: 'Offered term.' },
    { name: 'offerCharges', unit: 'minor units', description: 'Monthly charges of the offer.' },
    { name: 'switchingCosts', unit: 'minor units', description: 'Paid out of pocket at t = 0.' },
    {
      name: 'opportunityRate',
      unit: 'fraction per month',
      description: 'Discount rate for the present value; USER_ASSERTED or ESTIMATED.',
    },
  ],
  outputUnit: 'minor units; month number; boolean alert; truth class',
  rounding:
    'Schedules as amortization.french@1; present value computed at 40 digits and rounded ' +
    'HALF_EVEN to the minor unit once, at the end.',
  assumptions: [
    'The offer refinances exactly the outstanding balance.',
    'Charges are a fixed amount per month on each side.',
    'Break-even uses undiscounted cumulative savings; months past a schedule’s end count 0.',
    'Any ESTIMATED input makes the whole result ESTIMATED; GENERATED_NARRATIVE is refused.',
  ],
  reference: `${SPEC} §5.`,
  edgeCases: [
    'Identical offer with no switching costs: zero savings, break-even in month 1.',
    'Lower instalment but higher total paid: longerTermAlert.',
    'Savings that never cover the switching costs: breakEvenMonth null.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/refinance.ts#compareRefinance',
  testVectors: [
    {
      description: 'lower rate, same term, no switching costs: nominal savings',
      inputs: {
        balance: '800000000',
        currency: 'COP',
        currentRate: '0.025',
        currentPeriods: '24',
        offerRate: '0.017',
        offerPeriods: '24',
        switchingCosts: '0',
        opportunityRate: '0.008',
      },
      expected: '92570833',
    },
    {
      description: 'with COP 250,000 switching costs: nominal savings',
      inputs: {
        balance: '800000000',
        currency: 'COP',
        currentRate: '0.025',
        currentPeriods: '24',
        offerRate: '0.017',
        offerPeriods: '24',
        switchingCosts: '25000000',
        opportunityRate: '0.008',
      },
      expected: '67570833',
    },
    {
      description: 'longer term: the offer costs more in total',
      inputs: {
        balance: '800000000',
        currency: 'COP',
        currentRate: '0.02',
        currentPeriods: '12',
        offerRate: '0.018',
        offerPeriods: '48',
        switchingCosts: '0',
        opportunityRate: '0.008',
      },
      expected: '-293737803',
    },
  ],
});

registerFormula({
  formulaId: 'debt.payoff_plan',
  version: 1,
  purpose:
    'Month-by-month payoff simulation of several debts under AVALANCHE and SNOWBALL, so the ' +
    'user can compare both: months to debt-free, total interest and payoff order.',
  inputs: [
    { name: 'debts', unit: 'list', description: 'id, balance, monthly rate, minimum payment.' },
    { name: 'extra', unit: 'minor units', description: 'Monthly surplus above the minimums.' },
  ],
  outputUnit: 'months; minor units; ordered debt ids',
  rounding: 'Interest HALF_EVEN to the minor unit per debt per month.',
  assumptions: [
    'Constant monthly budget: Σ minimum payments + extra; cleared minimums roll over.',
    'Interest accrues before the month’s payment; rates stay constant.',
    'AVALANCHE: highest rate first. SNOWBALL: smallest current balance first. Ties keep ' +
      'the input order.',
  ],
  reference: `${SPEC} §6.`,
  edgeCases: [
    'Budget ≤ first month’s interest, or not cleared within 1,200 months: ' +
      'DEBT_NEVER_AMORTIZES.',
    'extra = 0: minimums still roll over as debts are cleared.',
    'Empty list, repeated ids or empty balances: INVALID_DEBT.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/payoff.ts#payoffPlan',
  testVectors: [
    {
      description: 'three debts with COP 500,000 extra: AVALANCHE total interest',
      inputs: {
        currency: 'COP',
        extra: '50000000',
        strategy: 'AVALANCHE',
        debts:
          'card-a:450000000:0.028:18000000;card-b:120000000:0.021:6000000;' +
          'loan-c:900000000:0.014:30000000',
      },
      expected: '220144615',
    },
    {
      description: 'three debts with COP 500,000 extra: SNOWBALL total interest',
      inputs: {
        currency: 'COP',
        extra: '50000000',
        strategy: 'SNOWBALL',
        debts:
          'card-a:450000000:0.028:18000000;card-b:120000000:0.021:6000000;' +
          'loan-c:900000000:0.014:30000000',
      },
      expected: '226287546',
    },
    {
      description: 'budget below the interest is rejected',
      inputs: {
        currency: 'COP',
        extra: '5000000',
        strategy: 'AVALANCHE',
        debts: 'card:1000000000:0.03:20000000',
      },
      expected: 'DEBT_NEVER_AMORTIZES',
    },
  ],
});
