/**
 * Formula Registry entries for the Colombian credit engine (task S1-01).
 * Spec: docs/financial-formulas/colombia-credit.md. Vectors: test/vectors/*.json,
 * generated by an independent Python `decimal` implementation (never by this code).
 */
import { registerFormula } from '../formula-registry.js';

const SPEC = 'docs/financial-formulas/colombia-credit.md';

registerFormula({
  formulaId: 'rate.convert',
  version: 1,
  purpose:
    'Convert an interest rate between quoting conventions (effective or nominal, ' +
    'compounding frequency, in arrears or in advance) through the effective annual rate.',
  inputs: [
    { name: 'rate', unit: 'fraction', description: 'The rate as quoted (0.023 = 2.3 %).' },
    { name: 'from', unit: 'quote', description: 'BASIS/PERIODS/TIMING of the input rate.' },
    { name: 'to', unit: 'quote', description: 'BASIS/PERIODS/TIMING of the output rate.' },
  ],
  outputUnit: 'fraction',
  rounding:
    'None inside the formula: 40 significant digits, half-even, at every step. Display ' +
    'rounding (2 decimals of a percentage) is an explicit caller decision.',
  assumptions: [
    'Nominal rates divide evenly into periodic rates: i_p = N / m.',
    'In advance and in arrears are related per period: i_v = i_a / (1 − i_a).',
    'Compounding frequencies are limited to m ∈ {1, 2, 4, 6, 12, 360, 365}.',
  ],
  reference: `${SPEC} §1; standard compound-interest equivalence of rates.`,
  edgeCases: [
    'A rate in advance of 100 % or more per period is rejected (RATE_OUT_OF_DOMAIN).',
    'Negative rates are rejected unless the caller passes allowNegative (spec §1).',
    'An unsupported frequency or malformed quote is rejected (UNSUPPORTED_QUOTE).',
    'Rate 0 converts to 0 in every convention.',
  ],
  implementationPath: 'packages/financial-engine/src/credit/rate.ts#convertRate',
  testVectors: [
    {
      description: '2.3 % MV → EA',
      inputs: { rate: '0.023', from: 'EFFECTIVE/12/ARREARS', to: 'EFFECTIVE/1/ARREARS' },
      expected: '0.3137344983996021269289886802331443',
    },
    {
      description: '24 % EA → MV',
      inputs: { rate: '0.24', from: 'EFFECTIVE/1/ARREARS', to: 'EFFECTIVE/12/ARREARS' },
      expected: '0.0180875824835106745313530841617514',
    },
    {
      description: '2 % monthly in advance → in arrears',
      inputs: { rate: '0.02', from: 'EFFECTIVE/12/ADVANCE', to: 'EFFECTIVE/12/ARREARS' },
      expected: '0.02040816326530612244897959183673469',
    },
    {
      description: 'rate 1 in advance is out of domain',
      inputs: { rate: '1', from: 'EFFECTIVE/12/ADVANCE', to: 'EFFECTIVE/1/ARREARS' },
      expected: 'RATE_OUT_OF_DOMAIN',
    },
  ],
});

registerFormula({
  formulaId: 'amortization.french',
  version: 1,
  purpose:
    'Fixed-instalment (French system) amortization schedule: instalment, per-period ' +
    'interest and principal, balance, total interest and total paid.',
  inputs: [
    { name: 'principal', unit: 'minor units', description: 'Amount lent, strictly positive.' },
    { name: 'currency', unit: 'ISO 4217', description: 'Currency of the principal.' },
    { name: 'rate', unit: 'fraction per period', description: 'Effective periodic rate ≥ 0.' },
    { name: 'periods', unit: 'integer', description: 'Number of instalments, 1..1200.' },
  ],
  outputUnit: 'minor units',
  rounding:
    'HALF_EVEN to the minor unit for the instalment and for each period’s interest. The ' +
    'last instalment pays the remaining balance plus its interest.',
  assumptions: [
    'Constant periodic rate for the whole term.',
    'Payments at the end of each period (in arrears).',
    'Insurance, fees and taxes are not part of this formula (see credit.total_cost).',
  ],
  reference: `${SPEC} §2; standard annuity-immediate present value.`,
  edgeCases: [
    'Rate 0: C = P / n, residue in the last instalment.',
    'One period: a single payment of principal plus interest.',
    'The last instalment may be above or below C by the accumulated rounding residue.',
    'Amounts too small for the term in whole minor units are rejected ' +
      '(UNAMORTIZABLE_IN_MINOR_UNITS).',
  ],
  implementationPath: 'packages/financial-engine/src/credit/french.ts#frenchAmortization',
  testVectors: [
    {
      description: 'COP 10,000,000 at 1.6 % MV over 36 months: instalment',
      inputs: { principal: '1000000000', currency: 'COP', rate: '0.016', periods: '36' },
      expected: '36757218',
    },
    {
      description: 'zero rate over 3 periods: instalment',
      inputs: { principal: '10000000', currency: 'COP', rate: '0', periods: '3' },
      expected: '3333333',
    },
    {
      description: '360 months at 0.95 % MV: instalment',
      inputs: { principal: '25000000000', currency: 'COP', rate: '0.0095', periods: '360' },
      expected: '245667153',
    },
    {
      description: 'zero periods is rejected',
      inputs: { principal: '100000', currency: 'COP', rate: '0.01', periods: '0' },
      expected: 'INVALID_TERM',
    },
  ],
});
