#!/usr/bin/env node
/**
 * FINCH agent-context sync — one source, every tool.
 *
 * Source of truth:
 *   .ai/rules/*.md          rules with front-matter (id, title, description, always, globs)
 *   .ai/skills/<name>/SKILL.md  skills with front-matter (name, description)
 *
 * Generated adapters (never edit by hand — they carry a GENERATED marker):
 *   Claude Code   .claude/skills/<name>/SKILL.md  + import block in CLAUDE.md
 *   Cursor        .cursor/rules/<id>.mdc          + .cursor/rules/skill-<name>.mdc
 *   Codex         index block in AGENTS.md (Codex reads AGENTS.md)
 *   Antigravity   .agent/rules/<id>.md            + .agent/workflows/<name>.md
 *
 * Usage:
 *   node scripts/ai-sync.mjs           write adapters
 *   node scripts/ai-sync.mjs --check   exit 1 if any adapter is missing, stale or edited by hand
 *
 * A context system that silently drifts is worse than none: the --check mode runs in CI.
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  mkdirSync,
  renameSync,
  rmSync,
  statSync,
} from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const MARKER =
  'GENERATED by scripts/ai-sync.mjs from .ai/ — do not edit; edit the source and re-run `pnpm ai:sync`.';
const BLOCK_START = '<!-- ai-sync:start -->';
const BLOCK_END = '<!-- ai-sync:end -->';

const targets = JSON.parse(readFileSync(join(ROOT, '.ai/targets.json'), 'utf8'));

// ---------------------------------------------------------------------------
// Front-matter (small YAML subset: scalars, booleans, string lists)
// ---------------------------------------------------------------------------
function parse(file) {
  const raw = readFileSync(file, 'utf8');
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(raw);
  if (!m) throw new Error(`${file}: missing front-matter`);
  const meta = {};
  let listKey = null;
  for (const line of m[1].split('\n')) {
    const item = /^\s+-\s+(.*)$/.exec(line);
    if (item && listKey) {
      meta[listKey].push(unquote(item[1]));
      continue;
    }
    const kv = /^([A-Za-z_][\w-]*):\s*(.*)$/.exec(line);
    if (!kv) continue;
    const [, key, value] = kv;
    if (value === '') {
      meta[key] = [];
      listKey = key;
    } else {
      listKey = null;
      meta[key] =
        value === '[]' ? [] : value === 'true' ? true : value === 'false' ? false : unquote(value);
    }
  }
  return { meta, body: m[2] };
}
const unquote = (s) => s.trim().replace(/^["']|["']$/g, '');

function requireFields(file, meta, fields) {
  for (const f of fields) {
    if (meta[f] === undefined || meta[f] === '')
      throw new Error(`${file}: front-matter field "${f}" is required`);
  }
}

// ---------------------------------------------------------------------------
// Load sources
// ---------------------------------------------------------------------------
const rulesDir = join(ROOT, '.ai/rules');
const rules = readdirSync(rulesDir)
  .filter((f) => f.endsWith('.md'))
  .sort()
  .map((f) => {
    const path = `.ai/rules/${f}`;
    const { meta, body } = parse(join(ROOT, path));
    requireFields(path, meta, ['id', 'title', 'description', 'always']);
    return { ...meta, globs: meta.globs ?? [], body, path };
  });

const skillsDir = join(ROOT, '.ai/skills');
const skills = readdirSync(skillsDir)
  .filter((d) => statSync(join(skillsDir, d)).isDirectory())
  .sort()
  .map((d) => {
    const path = `.ai/skills/${d}/SKILL.md`;
    const { meta, body } = parse(join(ROOT, path));
    requireFields(path, meta, ['name', 'description']);
    if (meta.name !== d)
      throw new Error(`${path}: name "${meta.name}" must equal its directory "${d}"`);
    if (meta.description.length > 1024)
      throw new Error(`${path}: description longer than 1024 characters`);
    return { ...meta, body, path };
  });

// ---------------------------------------------------------------------------
// Expected outputs
// ---------------------------------------------------------------------------
const files = new Map(); // relative path → content
const managedDirs = [];
const marker = (src) => `<!-- ${MARKER} Source: ${src} -->\n`;
const yamlList = (xs) => `[${xs.map((x) => JSON.stringify(x)).join(', ')}]`;

// Claude Code — skills
if (targets.claude) {
  const dir = targets.claude.skillsDir;
  managedDirs.push(dir);
  for (const s of skills) {
    files.set(
      `${dir}/${s.name}/SKILL.md`,
      `---\nname: ${s.name}\ndescription: ${JSON.stringify(s.description)}\n---\n\n${marker(s.path)}${s.body}`,
    );
  }
}

// Cursor — rules and agent-requested skill rules
if (targets.cursor) {
  const dir = targets.cursor.rulesDir;
  managedDirs.push(dir);
  for (const r of rules) {
    files.set(
      `${dir}/${r.id}.mdc`,
      `---\ndescription: ${JSON.stringify(r.description)}\nglobs: ${yamlList(r.globs)}\nalwaysApply: ${r.always}\n---\n\n${marker(r.path)}${r.body}`,
    );
  }
  for (const s of skills) {
    files.set(
      `${dir}/skill-${s.name}.mdc`,
      `---\ndescription: ${JSON.stringify(`Skill — ${s.description}`)}\nglobs: []\nalwaysApply: false\n---\n\n${marker(s.path)}${s.body}`,
    );
  }
}

// Antigravity — rules and workflows
if (targets.antigravity) {
  const { rulesDir: rd, workflowsDir: wd } = targets.antigravity;
  managedDirs.push(rd, wd);
  for (const r of rules) {
    files.set(
      `${rd}/${r.id}.md`,
      `---\ndescription: ${JSON.stringify(r.description)}\n---\n\n${marker(r.path)}${r.body}`,
    );
  }
  for (const s of skills) {
    files.set(
      `${wd}/${s.name}.md`,
      `---\ndescription: ${JSON.stringify(s.description)}\n---\n\n${marker(s.path)}${s.body}`,
    );
  }
}

// Index blocks inside CLAUDE.md and AGENTS.md
const alwaysRules = rules.filter((r) => r.always);
const scopedRules = rules.filter((r) => !r.always);
const skillTable = skills.map((s) => `| \`${s.name}\` | ${s.description} |`).join('\n');
const scopedTable = scopedRules
  .map((r) => `| \`${r.path}\` | ${r.globs.map((g) => `\`${g}\``).join(' ') || '—'} |`)
  .join('\n');

const claudeBlock = [
  BLOCK_START,
  `<!-- ${MARKER} -->`,
  '',
  '## Agent context (generated)',
  '',
  'Always-on rules, imported:',
  '',
  ...alwaysRules.map((r) => `@${r.path}`),
  '',
  'Scoped rules — read the file before working on matching paths:',
  '',
  '| Rule | Applies to |',
  '|---|---|',
  scopedTable,
  '',
  'Skills live in `.claude/skills/` (generated from `.ai/skills/`).',
  BLOCK_END,
].join('\n');

const agentsBlock = [
  BLOCK_START,
  `<!-- ${MARKER} -->`,
  '',
  '## 10. Agent context index (generated)',
  '',
  'Every agent (Codex, Claude, Cursor, Antigravity) uses the same sources in `.ai/`.',
  '',
  'Always-on rules: ' + alwaysRules.map((r) => `\`${r.path}\``).join(' · '),
  '',
  '| Scoped rule | Applies to |',
  '|---|---|',
  scopedTable,
  '',
  '| Skill (`.ai/skills/<name>/SKILL.md`) | Use it when |',
  '|---|---|',
  skillTable,
  BLOCK_END,
].join('\n');

function withBlock(file, block) {
  const current = readFileSync(join(ROOT, file), 'utf8');
  const start = current.indexOf(BLOCK_START);
  const end = current.indexOf(BLOCK_END);
  if (start === -1 || end === -1) return `${current.trimEnd()}\n\n${block}\n`;
  return `${current.slice(0, start)}${block}${current.slice(end + BLOCK_END.length)}`;
}
// Files that Prettier also formats are written already formatted, so --check stays stable.
async function formatted(file, content) {
  const options = (await prettier.resolveConfig(join(ROOT, file))) ?? {};
  return prettier.format(content, { ...options, filepath: join(ROOT, file) });
}
if (targets.claude) {
  const f = targets.claude.memoryFile;
  files.set(f, await formatted(f, withBlock(f, claudeBlock)));
}
if (targets.codex) {
  const f = targets.codex.agentsFile;
  files.set(f, await formatted(f, withBlock(f, agentsBlock)));
}

// ---------------------------------------------------------------------------
// Stale generated files (in managed dirs, carrying the marker, no longer expected)
// ---------------------------------------------------------------------------
// File access never checks-then-acts (CodeQL js/file-system-race): read and handle
// ENOENT instead of testing existence first, and write through a temp file + rename so
// an interrupted run never leaves a half-written adapter.
function isMissing(error) {
  return error instanceof Error && 'code' in error && error.code === 'ENOENT';
}

function readIfExists(abs) {
  try {
    return readFileSync(abs, 'utf8');
  } catch (error) {
    if (isMissing(error)) return null;
    throw error;
  }
}

function writeAtomic(abs, content) {
  mkdirSync(dirname(abs), { recursive: true });
  const tmp = `${abs}.${process.pid}.tmp`;
  writeFileSync(tmp, content, { flag: 'wx' });
  renameSync(tmp, abs);
}

function walk(dir) {
  let entries;
  try {
    entries = readdirSync(join(ROOT, dir), { withFileTypes: true });
  } catch (error) {
    if (isMissing(error)) return [];
    throw error;
  }
  return entries.flatMap((e) =>
    e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`],
  );
}
const stale = managedDirs
  .flatMap(walk)
  .filter((f) => !files.has(f) && readFileSync(join(ROOT, f), 'utf8').includes(MARKER));

// ---------------------------------------------------------------------------
// Write or check
// ---------------------------------------------------------------------------
const problems = [];
for (const [rel, content] of files) {
  const abs = join(ROOT, rel);
  const current = readIfExists(abs);
  if (current === content) continue;
  if (CHECK) problems.push(current === null ? `missing: ${rel}` : `out of date: ${rel}`);
  else writeAtomic(abs, content);
}
for (const rel of stale) {
  if (CHECK) problems.push(`stale: ${rel}`);
  else rmSync(join(ROOT, rel), { force: true });
}

const summary = `${rules.length} rules · ${skills.length} skills · ${files.size} adapter files`;
if (CHECK) {
  if (problems.length) {
    console.error(`ai-sync --check: agent context is out of sync (${summary})`);
    for (const p of problems) console.error(`  ✗ ${p}`);
    console.error('\nRun `pnpm ai:sync` and commit the result.');
    process.exit(1);
  }
  console.log(`ai-sync --check: in sync (${summary})`);
} else {
  console.log(
    `ai-sync: wrote adapters (${summary})${stale.length ? `, removed ${stale.length} stale` : ''}`,
  );
}
